<nav class="navbar navbar-default" role="navigation" style=" color:#fff; text-shadow:none; ">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle visible-xs-inline-block" data-toggle="collapse" data-target="#myNavbar" >
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
     <div class="navbar-header" style="margin-left: 20px;">
            <a class="navbar-brand" href="#"><img src="images/gdp.png" style="width: 125px;margin-left: -25px;"></a>
          </div>
    </div>
    <div class="collapse navbar-collapse navbar-ex1-collapse" id="myNavbar">
      <ul class="nav navbar-nav">         
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Modulos<b class="caret"></b>
                </a>
                <ul class="dropdown-menu">              
                  <li class="divider"></li>
                  <li><a href="#!" onclick="redirect('asignarmod')">Asignar</a></li>
                </ul>
             </li>
             <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <?php echo $_SESSION["user"]["CUENV_USUARIO"]; ?> <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><a href="#!" class="logout-action">Cerrar sesión</a></li>
                </ul>
             </li>
            </ul>
            </div>
  </div>
</nav>

