<!DOCTYPE html>
<html>
<head>
  <?php include("enlaces.phtml"); ?>
   <link href="<?php echo DOMAIN_ROOT ?>css/components.css" rel="stylesheet" id="style_components" type="text/css" />
    <link href="<?php echo DOMAIN_ROOT ?>css/plugins.css" rel="stylesheet" id="style_components" type="text/css" />
    
    <link href="<?php echo DOMAIN_ROOT ?>js/select2/css/select2-bootstrap.min.css" rel="stylesheet" id="style_components" type="text/css" />
    <script src="<?php echo DOMAIN_ROOT ?>js/select2/js/select2.js"></script>
</head>
<style>
    input[type="radio"], input[type="checkbox"] {
        margin: 0 !important;
    }
</style>
<body>
  <div data-role="page" id="admin-main-page" style="background-color: #DAE0EE">
  	<div data-role="header" style="background-image: url(images/bannergdp5.jpg); background-size: cover; background-repeat: no-repeat; background-position: 50% -186.152px;min-height:100px;">
       <?php  include("headeradm.phtml"); ?>
        <a href="#" data-rel="back" class="ui-btn-right ui-btn ui-btn-inline ui-mini ui-corner-all ui-btn-icon-left ui-icon-back">Volver</a>
    </div>
    <div role="main" class="ui-content">   
       <br><br>
       <div class="row">
           <div class="col-md-10 col-md-offset-1">
               
               <div class="portlet light bordered">
                    <div class="portlet-title">
                        <div class="caption">
                           Desactivar proveedores:
                        </div>
                    </div>
                   
                    <fieldset data-role="controlgroup" data-type="horizontal">
                        <input  type="radio" name="radio-choice-h-2 radio-val" onclick="selectopc(this)" id="radio-choice-h-2a" data-value="1">
                        <label for="radio-choice-h-2a">Por cliente</label>
                        <input  type="radio" name="radio-choice-h-2 radio-val" onclick="selectopc(this)" id="radio-choice-h-2b" data-value="2">
                        <label for="radio-choice-h-2b">Por canal</label>
                        <input  type="radio" name="radio-choice-h-2 radio-val" onclick="selectopc(this)" id="radio-choice-h-2c" data-value="3">
                        <label for="radio-choice-h-2c">Proveedor</label>
                        <input  type="radio" name="radio-choice-h-2 radio-val" onclick="selectopc(this)" id="radio-choice-h-2d" data-value="4">
                        <label for="radio-choice-h-2d">Todos</label>
                    </fieldset>
                       
                </div>
               
               

           </div>
           <div class="col-md-10 col-md-offset-1 ">
               
               
               <div class="portlet light bordered portlet-content-clie" style="display:none;">
                    <div class="portlet-title portlet-clientes">
                        <div class="caption">
                           Seleccionar clientes: 
                        
                        </div>
                        &nbsp; &nbsp; &nbsp; &nbsp;
                       
                    </div>
                   <div class="portlet-title">
                       <table id="" class="display" cellspacing="0" width="100%">
                    <thead>
                        <tr>                          
                            <th>Codigo</th>
                            <th>Cliente</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                     <tbody>                      
                        <?php 
                        foreach($data['CLIENTES'] as $d){ ?>
                        <tr>                            
                            <td><?php echo $d['CLIEV_IDCLIENTE']; ?></td>
                            <td><?php echo $d['CLIEV_NOMBRE']; ?></td>
                            <td><center><input type="checkbox" onclick="inptslect(this)" data-type="2" class="cliente inputs-checkbox" name="client[]" style="margin-top: -10px !important;" id="" value="<?php echo $d['CLIEV_IDCLIENTE']; ?>" class="client"></center></td>
                        </tr>
                        <?php } ?>
                    </tbody>
                </table>
                      
                   </div>
                   
                        
                </div>
               <div class="portlet light bordered portlet-content-prov" style="display:none;">
                    <div class="portlet-title portlet-proveedores">
                        <div class="caption">
                           Seleccionar Proveedores: 
                        
                        </div>
                        &nbsp; &nbsp; &nbsp; &nbsp;
                       
                    </div>
                   <div class="portlet-title">
                       <table id="" class="display" cellspacing="0" width="100%">
                    <thead>
                        <tr>                          
                            <th>Codigo</th>
                            <th>Proveedor</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                     <tbody>                      
                        <?php 
                        foreach($data['GROUPAA'] as $d){ ?>
                        <tr>                            
                            <td><?php echo $d['value']; ?></td>
                            <td><?php echo $d['descrip']; ?></td>
                            <td><center><input type="checkbox" onclick="inptslect(this)" data-type="1" class="provee inputs-checkbox" name="provee[]" style="margin-top: -10px !important;" id="" value="<?php echo $d['value']; ?>"></center></td>
                        </tr>
                        <?php } ?>
                    </tbody>
                </table>
                       
                   </div>
                   
                        
                </div>
               
               
               <div class="list-inputs">
               </div>
               
           </div>
        </div>
           <div data-role="footer" data-position="fixed" style="background-color: #3E3E3E; color: #FFFFFF">
                   <h4>Grupo Principal © <?php echo date("Y"); ?> </h4>

            </div>
    
      </div>
 </div>
<script>
$(function(){
    $('table.display').DataTable();
})
function inptslect(e){
    var t= $(e).data("type");
    var c= false;
    
    if(t==1){
        var v=$(e).val();
        $('.list-inputs').children('.prov-'+v).remove();
        if($(e).is(':checked')){
            $('.list-inputs').append("<input type='hidden' class='list-prov prov-"+v+"' value='"+v+"'>");
        }
        $('.list-prov').each(function(){
            c=true;
        })
        $(".portlet-proveedores").children(".btn-proveedor").remove();
        if(c==true){
            $(".portlet-proveedores").append(' <button onclick="saveprov(this)" data-value="4" class="btn btn-primary portlet-botton btn-proveedor btn-save-cont"> Guardar</button>');
        }
    }else if(t==2){
        var v=$(e).val();
        $('.list-inputs').children('.'+v).remove();
        if($(e).is(':checked')){
            $('.list-inputs').append("<input type='hidden' class='list-client "+v+"' value='"+v+"'>");
        }
        $('.list-client').each(function(){
            c=true;
        })
        $(".portlet-botton").remove();
        if(c==true){
            $(".portlet-clientes").append(' <button onclick="activeprov(this)" data-value="3" class="btn btn-primary portlet-botton btn-save-cont"> Continuar</button>');
        }
    }
    
}
function saveprov(){
    
    var inputs='';
     var prov=[];
    $(".list-prov").each(function(){
          prov.push($(this).val());
    });
    inputs=prov;
    if($(".list-canal").length > 0){
        var data= "tipo=canal&list="+inputs+"&canal="+$(".list-canal").val();
         $.ajax({
          url: server + "proveedor",
          type: "post",
            data: data,
             dataType: "json",
            }).done(function(response){
             alert("Proveedores desactivados para el canal seleccionado");
             console.log(response);
         });
        $(".list-prov").remove();
        $(".list-canal").remove();
    }else if($('.list-client').length > 0){
        var clie=[];
        $(".list-client").each(function(){
          clie.push($(this).val());
        });
        var data= "tipo=clients&list="+inputs+"&clients="+clie;
         $.ajax({
          url: server + "proveedor",
          type: "post",
            data: data,
             dataType: "json",
            }).done(function(response){
             alert("Proveedores desactivados");
             console.log(response);
         });
        $(".list-prov").remove();
        $('.list-client').remove();
        $('.btn-save-cont').remove();
        $(".portlet-content-prov").fadeOut();
        $(".portlet-content-clie").fadeOut();
        $('.inputs-checkbox').prop('checked', false);
        
    }else{
        var data= "tipo=provee&list="+inputs;
         $.ajax({
          url: server + "proveedor",
          type: "post",
            data: data,
             dataType: "json",
            }).done(function(response){
             alert("Proveedores desactivados");
             console.log(response);
         });
        $(".list-prov").remove();
        $('.btn-save-cont').remove();
        $(".portlet-content-prov").fadeOut();
        $('.inputs-checkbox').prop('checked', false);
    }
    
}
function activeprov(){
    $(".portlet-content-clie").fadeOut();
    infoAlert("Informacion","Seleccione los proveedores a desactiar a los clientes seleccionados");
    $(".portlet-content-prov").fadeIn();
    
}
function selectopc(e){
    $(".portlet-content-prov").fadeOut();
    $(".portlet-content-clie").fadeOut();
     var opc = $(e).data('value');
     switch(opc) {
         case 1:
             infoAlert("Informacion","Seleccione los clientes");
             $(".portlet-content-clie").fadeIn();
            break;
         case 2:
             $('.list-client').remove();
             $('.btn-save-cont').remove();
             $('.inputs-checkbox').prop('checked', false);
            $(".portlet-content-prov").fadeOut();
            $.ajax({
                  url: "<?php echo DOMAIN_ROOT ?>canales",
                  type: "GET",
                  dataType: "json",
                }).done(function(response){
                console.log(response);
                var select='<select id="canal" class="form-control">';
                var option='';
                var canales=[];
                for (var i=0; i<response.length; i++) {
                    option+="<option class='canal' value='"+response[i].CODIGCLI+"'>"+response[i].GRUPCLIE+"</option>";
                    canales[response[i].CODIGCLI]=response[i].GRUPCLIE;
                }
                select=select+option+'</select>';
                  $.jAlert({
                        'type': 'confirm', 
                        'confirmQuestion': select,
                        confirmBtnText:"SI",
                        denyBtnText:"NO",
                        'onConfirm': function(){
                            var canal=$('#canal').val();
                            $('.list-inputs').children('.list-canal').remove();
                            $('.list-inputs').append("<input type='hidden' class='list-canal' value='"+canal+"'>");
                            alert("Seleccione el proveedor a desactivar para el canal seleccionado");
                            $(".portlet-content-prov").fadeIn();
                        }
                    });
               });
            break;
         case 3:
             $(".list-canal").remove();
             $('.list-client').remove();
             $('.btn-save-cont').remove();
             $('.inputs-checkbox').prop('checked', false);
            var inputs='';
             var prov=[];
            $(".list-prov").each(function(){
                  prov.push($(this).val());
            });
            inputs=prov;
            $(".portlet-content-prov").fadeIn();
            break;
         case 4:
             $('.list-client').remove();
             $('.btn-save-cont').remove();
             $('.inputs-checkbox').prop('checked', false);
             var data= "tipo=all";
             $.ajax({
              url: server + "proveedor",
              type: "post",
                data: data,
              dataType: "json",
            }).done(function(response){
                 alert("Proveedores desactivados");
                 console.log(response);
             });
            break;
}
 }
</script>
</body>
</html>
