<!DOCTYPE html>
<html>
<head>
  <?php include("enlaces.phtml"); ?>

  <script>
    $(function(){
      $.ajax({
          url: server + "seller/x",
          type: "GET",
          dataType: "json"
      }).done(function(response){
        _tmp.clientEmpr = response.CRVV_CODIEMPR;        
      });
    })</script>
</head>

<body>
  <div data-role="page" id="seller-page" style="background-color: #DAE0EE">
  	<div data-role="header" style="background-image: url(<?php echo DOMAIN_ROOT ?>images/bannergdp5.jpg); background-size: cover; background-repeat: no-repeat; background-position: 50% -186.152px;min-height:100px;">
 
      <?php include("header_seller.phtml"); ?>
    <script src='<?php echo DOMAIN_ROOT ?>js/highcharts/js/highcharts.js'></script>
        <script src="<?php echo DOMAIN_ROOT ?>js/highcharts/js/modules/data.js"></script>
        <script src="<?php echo DOMAIN_ROOT ?>js/highcharts/js/modules/exporting.js"></script>
    <link rel="stylesheet" href="<?php echo DOMAIN_ROOT ?>js/daterangepicker/daterangepicker.css" />
    <script src="<?php echo DOMAIN_ROOT ?>js/daterangepicker/moment.js"></script>  
    <script src="<?php echo DOMAIN_ROOT ?>js/daterangepicker/daterangepicker.js"></script>
        <link href="<?php echo DOMAIN_ROOT ?>css/components.css" rel="stylesheet" id="style_components" type="text/css" />
    <link href="<?php echo DOMAIN_ROOT ?>css/plugins.css" rel="stylesheet" id="style_components" type="text/css" />
        <?php
            $meses=array(
                    '01'=>"Ene",
                    '02'=>"Feb",
                    '03'=>"Mar",
                    '04'=>"Abr",
                    '05'=>"May",
                    '06'=>"Jun",
                    '07'=>"Jul",
                    '08'=>"Ago",
                    '09'=>"Sep",
                    '10'=>"Oct",
                    '11'=>"Nov",
                    '12'=>"Dic");
            $catg='';
            $cajas="{name: 'Cajas',data: [";
            $bs="{name: 'Bs',data: [";
            
            foreach($data['range'] as $d){
                $catg.='"'.$meses[$d['MES']].'-'.$d['DIA'].'-'.$d['ANIO'].'",';
                $bs.=$d['PRECVENT'].',';
                $cajas.=$d['CAJAS'].',';
            }
            $catg=substr($catg, 0, -1);
            $cajas=substr($cajas, 0, -1);
            $bs=substr($bs, 0, -1);
            $cajas.="]}";
            $bs.="]}";
            $p=count($data['range']);
        ?>
    </div>
    <div role="main" class="ui-content">
      <ul data-role="listview" data-inset="true">
        <!-- <li><a href="#seller-orders-page">Mis Pedidos</a></li> -->
        <li><a href="pedidos/<?php echo $_SESSION['user']['info']['VENDV_IDVENDEDOR']; ?>">Pedidos</a></li>
        <li><a href="#seller-client-orders-page">Pedidos de clientes</a></li>
        <li><a href="#client-list-page">Tomar Pedido</a></li>
      </ul>
        <div class="row">
        <div class="row col-md-10 col-md-offset-1">
            
        <div>
            <div class="portlet light">
                <div class="portlet-title">
                            <div class="caption font-green-sharp">
                                <i class="icon-speech font-green-sharp"></i>
                                <span class="caption-subject">
                                    <h4>Resumen de ventas del dia: <?php echo $data['range'][$p-1]['FECHA']; ?></h4>
                                    <h6>Ultimo dia que la ruta realizó pedidos</h6>
                                </span>
                            </div>
                        </div>
            <div class="portlet-body">
                            <div class="caption font-blue-hoki">
            <table class="table table-bordered table-striped table-condensed flip-content">
                    <tr><th rowspan="2" style="text-align:center;vertical-align: middle;">Ventas del dia</th><th>Cajas</th><th>Bs</th></tr>
                    <tr><td><?php echo $data['range'][$p-1]['CAJAS']; ?></td><td><?php echo $data['range'][$p-1]['PRECVENT']; ?></td></tr>

            </table>
                </div>
                </div>
                </div>
        </div>
        <div id="container"></div>
        
        <br>
        <br>
        <!--Grafica de ventas por grupo-->
        
         <div>
            <div class="portlet light">
                <div class="portlet-title">
                            <div class="caption font-green-sharp">
                                <i class="icon-speech font-green-sharp"></i>
                                <span class="caption-subject">
                                    <h4>Resumen de ventas por grupo <?php echo $data['range'][$p-1]['FECHA']; ?></h4>
                                </span>
                            </div>
                        </div>
            <div class="portlet-body">
                <div class="caption font-blue-hoki">
                    <?php if(!empty($data['grupo'])){ ?>
                <table id="datatable" class="table  table-bordered table-striped table-condensed flip-content">
                        <thead>
                            <tr>
                                <th></th>
                                <?php 
                                $dtg='';
                                foreach($data['grupo'] as $g){ 
                                    $dtg.="'".$g['DESCGRUP']."',";
                                ?>
                                    <th><?php echo $g['DESCGRUP']; ?></th>
                                <?php }
                                    $dtg=substr($dtg, 0, -1);
                                ?>
                            </tr>
                        </thead>
                    <tbody>
                        <tr>
                            <td>Cajas</td>
                            <?php 
                            $dtc='';
                            foreach($data['grupo'] as $g){ 
                            $dtc.=$g['cajas'].",";
                            ?>
                                <td><?php echo $g['cajas']; ?></td>
                            <?php }
                            $dtc=substr($dtc, 0, -1);
                            ?>
                        </tr>
                        <tr>
                            <td>Bs</td>
                            <?php 
                            $dtv='';
                            foreach($data['grupo'] as $g){ 
                            $dtv.=$g['totalVenta'].",";
                            ?>
                                <td><?php echo $g['totalVenta']; ?></td>
                            <?php }
                            $dtv=substr($dtv, 0, -1);
                            ?>
                        </tr>
                    </tbody>

                </table>
                    <?php } ?>
                   
                </div>
                </div>
                </div>
        </div>
    </div>
    <div class="row col-md-12">
        <div id="conten1" class="col-md-6 col-md-offset-1 " style="min-width: 310px; height: 400px; margin: 0 auto"></div>
        <div id="conten2" class="col-md-6 col-md-offset-1 " style="min-width: 310px; height: 400px; margin: 0 auto"></div>
    </div>
            <script>
            
             var chart = Highcharts.chart('conten1', {

    title: {
        text: 'Resumen de ventas en cajas'
    },

    xAxis: {
        categories: [<?php echo $dtg ?>]
    },yAxis: {
                title: {
                    text: 'Cajas'
                }
            },

    series: [{
        name: 'Cajas',
        type: 'column',
        colorByPoint: true,
        data: [<?php echo $dtc ?>],
        showInLegend: false
    }]

});
var chart = Highcharts.chart('conten2', {

    title: {
        text: 'Resumen de ventas en Bs '
    },

    xAxis: {
        categories: [<?php echo $dtg ?>]
    },
    yAxis: {
                title: {
                    text: 'Bs'
                }
            },

    series: [{
        name: 'Bs',
        type: 'column',
        colorByPoint: true,
        data: [<?php echo $dtv ?>],
        showInLegend: false
    }]

});
            </script>

        
    </div>
    </div>
  	<div data-role="footer" data-position="fixed" style="background-color: #0188C8; color: #FFFFFF">
      <h4>Grupo Principal © <?php echo date("Y"); ?></h4>
    </div>
<?php
    if(!empty($data['range'])){
?>
<script>
    $(function(){
        Highcharts.chart('container', {
            chart: {
                type: 'line'
            },
            title: {
                text: 'Ventas realizadas por Cajas y Bs'
            },
            subtitle: {
                text: 'Desde: <?php echo $data['range'][0]['desde'] ?> Hasta: <?php echo date("Y-m-d"); ?>'
            },
            xAxis: {
                categories: [<?php echo $catg; ?>]
            },
            yAxis: {
                title: {
                    text: 'Ventas Cajas/Bs'
                }
            },
            plotOptions: {
                line: {
                    dataLabels: {
                        enabled: true
                    },
                    enableMouseTracking: false
                }
            },
            series: [<?php echo  $bs; ?>, <?php echo $cajas; ?>]
        });
        



    
    });
</script>
<?php
      }
?>
  </div>

  <div data-role="page" id="seller-orders-page" style="background-color: #DAE0EE">
  	<div data-role="header" style="background-image: url(<?php echo DOMAIN_ROOT ?>images/bannergdp5.jpg); background-size: cover; background-repeat: no-repeat; background-position: 50% -186.152px;min-height:100px;">
 
      <a href="#seller-page" style="z-index:999;" class="ui-btn-right ui-btn ui-btn-inline ui-mini ui-corner-all ui-btn-icon-left ui-icon-back">Volver</a>
      <?php include("header_seller.phtml"); ?>
    </div>
    <div role="main" class="ui-content">
      <div data-role="collapsibleset">
        <div data-role="collapsible" data-collapsed-icon="user" data-expanded-icon="user">
          <h2>Pedidos Pendientes por procesar</h2>
          <ul data-type="PENDIENTE" data-role="listview" data-inset="true" data-split-icon="delete">
        </div>        
        <div data-role="collapsible" data-collapsed-icon="delete" data-expanded-icon="delete">
          <h2>Pedidos Rechazados por la empresa</h2>
          <ul data-type="RECHAZADO" data-role="listview" data-inset="true">
        </div>
        <div data-role="collapsible" data-collapsed-icon="arrow-u" data-expanded-icon="arrow-u">
          <h2>Pedidos Enviados a la empresa</h2>
          <ul data-type="ENCURSO" data-role="listview" data-inset="true">
        </div>
        <div data-role="collapsible" data-collapsed-icon="check" data-expanded-icon="check">
          <h2>Pedidos Procesados por la empresa</h2>
          <ul data-type="PROCESADO" data-role="listview" data-inset="true">
        </div>
      </div>
    </div>
  	<div data-role="footer" data-position="fixed" style="background-color: #0188C8; color: #FFFFFF">
      <h4>Grupo Principal © <?php echo date("Y"); ?></h4>
    </div>
  </div>
  <div data-role="page" id="seller-client-orders-page" style="background-color: #DAE0EE">
    <div data-role="header" style="background-image: url(<?php echo DOMAIN_ROOT ?>images/bannergdp5.jpg); background-size: cover; background-repeat: no-repeat; background-position: 50% -186.152px;min-height:100px;">
 
      <a href="#seller-page" style="z-index:999;" class="ui-btn-right ui-btn ui-btn-inline ui-mini ui-corner-all ui-btn-icon-left ui-icon-back">Volver</a>
      <?php include("header_seller.phtml"); ?>
    </div>
    <div role="main" class="ui-content">
      <div data-role="collapsibleset">
        <div data-role="collapsible" data-collapsed-icon="user" data-expanded-icon="user">
          <h2>Pedidos Pendientes por procesar</h2>
          <ul data-type="PENDIENTE" data-role="listview" data-inset="true" data-split-icon="delete">
        </div>        
        <div data-role="collapsible" data-collapsed-icon="delete" data-expanded-icon="delete">
          <h2>Pedidos Rechazados por la empresa</h2>
          <ul data-type="RECHAZADO" data-role="listview" data-inset="true">
        </div>
        <div data-role="collapsible" data-collapsed-icon="arrow-u" data-expanded-icon="arrow-u">
          <h2>Pedidos Enviados a la empresa</h2>
          <ul data-type="PENDIENTE" data-role="listview" data-inset="true">
        </div>
        <div data-role="collapsible" data-collapsed-icon="check" data-expanded-icon="check">
          <h2>Pedidos Procesados por la empresa</h2>
          <ul data-type="PROCESADO" data-role="listview" data-inset="true">
        </div>
      </div>
    </div>
    <div data-role="footer" data-position="fixed" style="background-color: #0188C8; color: #FFFFFF">
      <h4>Grupo Principal © <?php echo date("Y"); ?></h4>
    </div>
  </div>

  <div data-role="page" id="order-details-page">
      
    <div data-role="header" style="background-image: url(<?php echo DOMAIN_ROOT ?>images/bannergdp5.jpg); background-size: cover; background-repeat: no-repeat; background-position: 50% -186.152px;min-height:100px;">
        <?php include("header_seller.phtml"); ?>
        
        
      
      <div data-role="controlgroup" data-type="horizontal" class="ui-mini ui-btn-right">
          <a href="#" style="z-index:999;" data-rel="back" class="ui-btn ui-btn-inline ui-mini ui-corner-all ui-btn-icon-left ui-icon-back">Volver</a>
        <a href="#new-request-page" class="btoEditar ui-btn ui-btn-inline ui-mini ui-corner-all ui-btn-icon-left ui-icon-edit">Editar</a>        
      </div>
    </div>
      
    <div role="main" class="ui-content">
      <p>Número: <span class="order-id"></span></p>
      <p>Fecha: <span class="order-date"></span></p>
      <p>Cliente: <span class="order-client-name"></span></p>
      <p>Ruta: <span class="order-seller-name"></span></p>
      <table class="order_details">
        <thead>
          <th>Codigo</th>
          <th>Descrip.</th>
          <th>Cantidad</th>
          <th>% Desc</th>
          <th>Precio</th>
        </thead>
        <tbody>
        </tbody>
      </table>
      <table class="simpleCart_totals" align="right" style="font-size:12px;">
        <tr>
          <th >Cantidad:</th>
          <td><span class="order-items"></span></td>
        </tr>
        <tr>
          <th >Descuentos:</th>
          <td><span class="simpleCart_desc"></span></td>
        </tr>
        <tr>
          <th>Sub-Total:</th>
          <td><span class="order-subtotal"></span></td>
        </tr>
        <tr>
          <th>I.V.A.:</th>
          <td><span class="order-iva"></span></td>
        </tr>
        <tr>
          <th>Total:</th>
          <td><span class="order-total"></span></td>
        </tr>
      </table>
    </div>
  	<div data-role="footer" data-position="fixed" style="background-color: #0188C8; color: #FFFFFF">
      <h4>Grupo Principal © <?php echo date("Y"); ?></h4>
    </div>
  </div>

  <div data-role="page" id="client-list-page" style="background-color: #DAE0EE">
  	<div data-role="header" style="background-image: url(<?php echo DOMAIN_ROOT ?>images/bannergdp5.jpg); background-size: cover; background-repeat: no-repeat; background-position: 50% -186.152px;min-height:100px;">
      <a href="#seller-page" style="z-index:999;" class="ui-btn-right ui-btn ui-btn-inline ui-mini ui-corner-all ui-btn-icon-left ui-icon-back">Volver</a>
      <?php include("header_seller.phtml"); ?>
    </div>
    <div role="main" class="ui-content">
      <ul data-filter="true" data-filter-placeholder="Buscar Cliente..." data-role="listview" data-inset="true"></ul>
    </div>
  	<div data-role="footer" data-position="fixed" style="background-color: #0188C8; color: #FFFFFF">
      <h4>Grupo Principal © <?php echo date("Y"); ?></h4>
    </div>
  </div>

  <div data-role="page" id="new-request-page">
  	<div data-role="header" style="background-image: url(<?php echo DOMAIN_ROOT ?>images/bannergdp5.jpg); background-size: cover; background-repeat: no-repeat; background-position: 50% -186.152px;min-height:100px;">
           <?php include("header_seller.phtml"); ?>
      <div data-role="controlgroup" data-type="horizontal" class="ui-mini ui-btn-right">
        <a href="#cart-panel" class="ui-btn ui-btn-inline ui-mini ui-corner-all ui-btn-icon-right ui-icon-action">Totalizar</a>
        <a href="#client-list-page" class="bto_volver ui-btn ui-btn-inline ui-mini ui-corner-all ui-btn-icon-left ui-icon-back">Volver</a>

      </div>
      <div data-role="navbar" class="group-control">
        <div class="ui-grid-a ui-responsive">
          <div class="ui-grid-c ui-block-a ui-responsive" style="font-size:12px;">
            <div class="ui-block-a"><span>Cantidad: </span><span class="simpleCart_quantity1"></span> </div>
            <div class="ui-block-c"><span>Desc.: </span><span class="simpleCart_desc"></span></div>
            <div class="ui-block-b"><span>Sub-Total: </span><span class="simpleCart_grandTotal"></span></div>
            <div class="ui-block-c"><span>I.V.A.: </span><span class="simpleCart_iva"></span></div>
            <div class="ui-block-d"><span>Total: </span><span class="simpleCart_finalTotal"></span></div>
          </div>
          <div class="ui-block-b ui-responsive">
          </div>
        </div>
        <ul>
          <li><input id="searchField" type="text" placeholder="Buscar producto..." /></li>
          <li><select id="group-aa"><option value="all">TODOS</option></select></li>
          <li><select id="group-ab"><option value="all">TODOS</option></select></li>
          <!--<li><select id="group-ac"><option value="all">TODOS</option></select></li>-->
        </ul>
       <!-- <div class="ui-grid-solo">
          <div class="ui-block-a"><input id="searchField" type="text" placeholder="Buscar producto..." /></div>
        </div>-->
        <div class="ui-grid-solo" style="font-size:14px;">
          <span class="simpleCart_paginas"></span>
          <a class="bto_primera" href="#">Primera</a>
          <a class="bto_anterior" href="#">Anterior</a>
          <a class="bto_siguiente" href="#">Siguiente</a>
          <a class="bto_final" href="#">Final</a>
        </div>    
      </div>
    </div>    
    <div role="main" class="ui-content" style="background-color: #DAE0EE">      
      <div class="ui-grid-c ui-responsive">
        <div class="ui-block-a" id="CardsBlockA"></div>
        <div class="ui-block-b" id="CardsBlockB"></div>
        <div class="ui-block-c" id="CardsBlockC"></div>
        <div class="ui-block-d" id="CardsBlockD"></div>
      </div>
    </div>
  	<div data-role="footer" data-position="fixed" style="background-color: #0188C8; color: #FFFFFF">    
      <h4>Grupo Principal © <?php echo date("Y"); ?></h4>
    </div>
    <div data-role="panel" data-position="right" data-display="overlay" id="cart-panel">
      <div class="ui-grid-solo">
        <div class="ui-block-a">
          <a href="#checkout-page" class="ui-btn ui-corner-all ui-btn-icon-right ui-icon-action">Procesar</a>
        </div>
      </div>
      <div class="ui-grid-solo">
        <div class="ui-block-a cart-items"></div>
      </div>
      <div class="ui-grid-solo">
        <table class="simpleCart_totals" align="right" style="font-size:12px;">
          <tr>
            <th >Cantidad:</th>
            <td><span class="simpleCart_quantity1"></span></td>
          </tr>
          <tr>
            <th >Descuentos:</th>
            <td><span class="simpleCart_desc"></span></td>
          </tr>
          <tr>
            <th>Sub-Total:</th>
            <td><span class="simpleCart_grandTotal"></span></td>
          </tr>
          <tr>
            <th>I.V.A.:</th>
            <td><span class="simpleCart_iva"></span></td>
          </tr>
          <tr>
            <th>Total:</th>
            <td><span class="simpleCart_finalTotal"></span></td>
          </tr>
        </table>
      </div>      
    </div>
  </div>

  <div data-role="page" id="checkout-page">
  	<div data-role="header" style="background-image: url(<?php echo DOMAIN_ROOT ?>images/bannergdp5.jpg); background-size: cover; background-repeat: no-repeat; background-position: 50% -186.152px;min-height:100px;">
           <?php include("header_seller.phtml"); ?>
        <div data-role="controlgroup" data-type="horizontal" class="ui-mini ui-btn-right">
            <a href="#client-list-page" class=" ui-btn ui-btn-inline ui-mini ui-corner-all ui-icon-check ui-btn-checkout-s">Procesar</a>
            <a href="#" data-rel="back"  style="z-index:999;" class="bto_volver ui-btn ui-btn-inline ui-mini ui-corner-all ui-btn-icon-left ui-icon-back">Volver</a>
        </div>
    </div>
    <div role="main" class="ui-content">
      <div class="cart-items"></div>
      <table class="simpleCart_totals" align="right" style="font-size:12px;">
        <tr>
          <th >Cantidad:</th>
          <td><span class="simpleCart_quantity1"></span></td>
        </tr>
        <tr>
          <th >Descuentos:</th>
          <td><span class="simpleCart_desc"></span></td>
        </tr>
        <tr>
          <th>Sub-Total:</th>
          <td><span class="simpleCart_grandTotal"></span></td>
        </tr>
        <tr>
          <th>I.V.A.:</th>
          <td><span class="simpleCart_iva"></span></td>
        </tr>
        <tr>
          <th>Total:</th>
          <td><span class="simpleCart_finalTotal"></span></td>
        </tr>
      </table>
    </div>
  	<div data-role="footer" data-position="fixed" style="background-color: #0188C8; color: #FFFFFF">
      <h4>Grupo Principal © <?php echo date("Y"); ?></h4>
    </div>
  </div>
</body>
</html>
