<nav class="navbar navbar-default" role="navigation" style=" color:#fff; text-shadow:none; ">
    <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle visible-xs-inline-block" data-toggle="collapse" data-target="#myNavbar" >
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>                        
          </button>
         <div class="navbar-header" style="margin-left: 20px;">
                <a class="navbar-brand" href="#"><img src="<?php echo DOMAIN_ROOT ?>images/gdp.png" style="width: 125px;margin-left: -25px;"></a>
              </div>
        </div>

         <div class="collapse navbar-collapse navbar-ex1-collapse" id="myNavbar">
          <ul class="nav navbar-nav">
            <li ><a href="#!" onclick="redirect('./')" >Principal</a></li> 
            <li ><a href="#!" onclick="redirect('cheques')" >Cheques devueltos</a></li> 
            <li ><a href="#!" onclick="redirect('pago')" >Pagos</a></li> 
              
             <?php
              if(count($_SESSION['user']['rutas'])>1){
              ?>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Ruta <?php echo $_SESSION['user']['details']['CRVV_IDVENDEDOR']; ?> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <?php foreach($_SESSION['user']['rutas'] as $r ){ ?>
              <li><a href="#" onclick="changeruta(<?php echo $r['CODIRUTA'] ?>)">Ruta: <?php echo $r['CODIRUTA'] ?></a></li>
                <?php } ?>
            </ul>
         </li>
              <?php
              }
              ?>
              
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <?php echo $_SESSION["user"]["CUENV_USUARIO"]; ?> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li ><a href="https://www.gdp.com.ve/iniciar/"  >Inicio</a></li>
              <li><a href="#!" class="logout-action">Cerrar sesión</a></li>
            </ul>
         </li>
        </ul>
        </div>
    </div>
</nav>
<script>
function changeruta(ruta){
    $.post('../dologin.php?ruta='+ruta,'ruta='+ruta,function(response){
               window.location.assign("./");
        });
}
</script>