<?php  
if($_SESSION["user"]['DEPARTAMENTO']=='GDP Tecnologia'){
?>
<nav class="navbar navbar-default " role="navigation" style=" color:#fff; text-shadow:none; ">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle visible-xs-inline-block" data-toggle="collapse" data-target="#myNavbar" >
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
     <div class="navbar-header" style="margin-left: 20px;">
            <a class="navbar-brand" href="#"><img src="<?php echo DOMAIN_ROOT ?>images/gdp.png" style="width: 125px;margin-left: -25px;"></a>
          </div>
    </div>
    <div class="collapse navbar-collapse navbar-ex1-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
          <li ><a href="#!" onclick="redirect('./')" >Principal</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Modulos<b class="caret"></b>
                </a>
                <ul class="dropdown-menu">                              
                  <li><a href="#!" onclick="redirect('asignarmod')">Clientes</a></li>
                  <li><a href="#!" onclick="redirect('asignaremp')">Empleados</a></li>
                </ul>
             </li>
          <li><a href="#" onclick='redirect("promociones-lista")' >Promociones</a></li>
          
        
             <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <?php echo $_SESSION["user"]["CUENV_USUARIO"]; ?> <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li ><a href="https://www.gdp.com.ve/iniciar/"  >Inicio</a></li>
                  <li><a href="#!" class="logout-action">Cerrar sesión</a></li>
                </ul>
             </li>
            </ul>
            </div>
  </div>
</nav>
<?php
}elseif($_SESSION["user"]['DEPARTAMENTO'] == 'Ventas'){
?>

<nav class="navbar navbar-default" role="navigation" style=" color:#fff; text-shadow:none; ">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle visible-xs-inline-block" data-toggle="collapse" data-target="#myNavbar" >
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
     <div class="navbar-header" style="margin-left: 20px;">
            <a class="navbar-brand" href="#"><img src="images/gdp.png" style="width: 125px;margin-left: -25px;"></a>
          </div>
    </div>
    <div class="collapse navbar-collapse navbar-ex1-collapse" id="myNavbar">
      <ul class="nav navbar-nav">         
             
             <li ><a href="#!" onclick="redirect('./')" >Principal</a></li>
             <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Administrar <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><a href="#!" onclick='redirect("proveedores")'>Proveedores</a></li>
                  <li class="divider"></li>
                  <li><a href="#!" onclick='redirect("limite")'>Limites</a></li>
                </ul>
             </li>
          <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <?php echo $_SESSION["user"]["CUENV_USUARIO"]; ?> <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li ><a href="https://www.gdp.com.ve/iniciar/"  >Inicio</a></li>
                  <li><a href="#!" class="logout-action">Cerrar sesión</a></li>
                </ul>
             </li>
            </ul>
            </div>
  </div>
</nav>

<?php
}else{
?>
<nav class="navbar navbar-default" role="navigation" style=" color:#fff; text-shadow:none; ">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle visible-xs-inline-block" data-toggle="collapse" data-target="#myNavbar" >
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
     <div class="navbar-header" style="margin-left: 20px;">
            <a class="navbar-brand" href="#"><img src="images/gdp.png" style="width: 125px;margin-left: -25px;"></a>
          </div>
    </div>
    <div class="collapse navbar-collapse navbar-ex1-collapse" id="myNavbar">
      <ul class="nav navbar-nav">         
             
             <li ><a href="#!" onclick="redirect('./')" >Principal</a></li>
             <li><a href="#" onclick='redirect("fpagosday")' >Pagos del día</a></li>
          <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <?php echo $_SESSION["user"]["CUENV_USUARIO"]; ?> <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li ><a href="https://www.gdp.com.ve/iniciar/"  >Inicio</a></li>
                  <li><a href="#!" class="logout-action">Cerrar sesión</a></li>
                </ul>
             </li>
            </ul>
            </div>
  </div>
</nav>
<?php
     }
?>