<!DOCTYPE html>
<html>
<head>
 <?php include("enlaces.phtml"); ?>
</head>

<body>
 <div data-role="page" id="admin-ini-page" >
  	<div data-role="header" style="background-image: url(images/bannergdp5.jpg); background-size: cover; background-repeat: no-repeat; background-position: 50% -186.152px;min-height:100px;">
        <?php include("header.phtml"); ?>
    </div>
        <h2 style="text-align: center;">Pagos de Factura</h2>
    
      <!-- ## Contenedor principal ## -->
    <div role="main" class="ui-content row">
    <div class="row">
    <div class="col-md-10 col-md-offset-1">
       <div role="main" class="ui-content">
            <div data-role="collapsibleset">
			   <div class="table-responsive">  
			     <table id="" class="table table-hover table-condensed" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>N° Factura</th>
                            <th>Fecha</th>
                            <th>N° Referencia</th>
                            <th>Banco</th>			                            
                            <th style="text-align: right">Monto</th> 
                            <th>&nbsp;</th>                                   
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach($data as $d){      ?>  			                                      
                        <tr>
                            <td><?php echo $d['NUMEDOCU']; ?></td>
                            <td><?php echo $d['FECHA']; ?></td>
                            <td><?php echo $d['DESCRI']; ?></td>
                            <td><?php echo $d['NOMBBANC']; ?></td>			                          
                            <td style="text-align: right"><?php echo number_format($d['MONTO'],2); ?></td>  
                            <td style="text-align: center;"> <a href="../cpantalla/<?php echo $d['id']; ?>" class="btn btn-default btn-sm" data-role="button" title="Captura de pantalla" transition="flip" data-rel="dialog" data-theme="d"> <span class="glyphicon glyphicon-picture"></span></a></td>                                       
                        </tr>
                        <?php } ?>


                    </tbody>			       
			    </table>
			   </div>
			</div>
	     </div>

  
	</div>

</div>    
</div>    
</div>
</body>
</html>
