
<!DOCTYPE html>
<html>
<head>
  <?php include("enlaces.phtml"); ?>
</head>

<body>

  <div data-role="page" id="admin-ini-page" >
  	<div data-role="header" style="background-image: url(images/bannergdp5.jpg); background-size: cover; background-repeat: no-repeat; background-position: 50% -186.152px;min-height:100px;">
        <?php include("header.phtml"); ?>
    </div>
      <!-- ## Contenedor principal ## -->
    <div role="main" class="ui-content">